#################################################################
# teamName used for argocd applicaiton names and namespace names.
#################################################################
teamName: platform
#################################################################
# default Values for gitops-payload helm chart
#################################################################
defaults:
  # argcod application defaults
  finalizers: resources-finalizer.argocd.argoproj.io
  gitopsNamespace: openshift-gitops
  # Helm defaults
  helmRepoUrl: https://pages.github.service.anz/ics/helm-charts
  path: charts
  chart: gitops-namespaces-payload
  targetRevision: 0.1.8
  # Vault plugin defaults.
  plugin: false
  AWS_REGION: "ap-southeast-2"
  AVP_TYPE: "awssecretsmanager"
#################################################################
# INFRASTRUCTURE Charts to be deployed.
################################################################# 
applications:
  - name: payments
    appNumber: "1234"
    gitopsCreate: true
    gitRepoUrl: https://github/cluster-config.git
    gitPath: nonprod/namespaces/payments-1234.yaml
    appProject:
      adGroup: PFAUTHAD
      repos:
      - 'https://pages.github/helm-charts'
      - 'https://github/cluster-configs.git'
  - name: accounting
    appNumber: "5678"
    gitopsCreate: true
    gitRepoUrl: https://github/cluster-config.git
    gitPath: nonprod/namespaces/accounting-5678.yaml
    appProject:
      adGroup: PFAUTHAD
      repos:
      - 'https://pages.github/helm-charts'
      - 'https://github/cluster-configs.git'
    