#################################################################
# teamName used for argocd applicaiton names and namespace names.
#################################################################
teamName: platform
#################################################################
# default Values for app-of-apps-infrastructure helm chart
#################################################################
defaults:
  # argcod application defaults
  finalizers: resources-finalizer.argocd.argoproj.io
  gitopsNamespace: openshift-gitops
  # Helm defaults
  helmRepoUrl: https://rosa-hcp-dedicated-vpc.github.io/helm-repository
  path: charts
  chart: app-of-apps-namespaces
  targetRevision: 0.3.3
  # Vault plugin defaults.
  plugin: false
  AWS_REGION: "ap-southeast-2"
  AVP_TYPE: "awssecretsmanager"
#################################################################
# INFRASTRUCTURE Charts to be deployed.
################################################################# 
applications: